import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.SITE_URL || 'http://127.0.0.1:4180/';
const output = fileURLToPath(new URL('../verification/', import.meta.url));
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true, executablePath: process.env.BROWSER_EXECUTABLE });
const errors = [];
const failedResponses = [];
const report = { url: base, layouts: [], workflows: {}, accessibility: {}, errors, failedResponses };
function watch(page) {
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  page.on('response', response => { if (response.status() >= 400) failedResponses.push(`${response.status()} ${response.url()}`); });
}
async function jump(page, selector) {
  await page.locator(selector).evaluate(element => element.scrollIntoView({ behavior: 'instant', block: 'start' }));
  await page.waitForTimeout(1100);
}
async function reveal(page) {
  for (const selector of ['#intention', '#object', '#details', '.vision', '#development', '.closing', '.footer']) await jump(page, selector);
}
async function layout(page, name, width, height, screenshot = false) {
  await page.setViewportSize({ width, height });
  await page.goto(base, { waitUntil: 'networkidle' });
  await page.waitForTimeout(1400);
  assert.equal(await page.getByRole('heading', { level: 1 }).getAttribute('aria-label'), 'Nurture Everyday — The everyday, considered.');
  assert.equal(await page.locator('main').count(), 1);
  assert(await page.locator('.hero-angle').evaluate(img => img.complete && img.naturalWidth > 0));
  if (screenshot) await page.screenshot({ path: path.join(output, `${name}-hero.png`) });
  await reveal(page);
  const dimensions = await page.evaluate(() => ({ viewport: innerWidth, document: document.documentElement.scrollWidth, pageHeight: document.documentElement.scrollHeight, brokenImages: [...document.querySelectorAll('main img')].filter(img => !img.complete || !img.naturalWidth).map(img => img.src) }));
  assert(dimensions.document <= dimensions.viewport + 1, `${name}: horizontal overflow ${JSON.stringify(dimensions)}`);
  assert.equal(dimensions.brokenImages.length, 0, `${name}: broken images`);
  report.layouts.push({ name, width, height, ...dimensions });
  if (screenshot) await page.screenshot({ path: path.join(output, `${name}-full.png`), fullPage: true });
}
try {
  const desktopContext = await browser.newContext({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
  const desktop = await desktopContext.newPage();
  watch(desktop);
  await layout(desktop, 'desktop', 1440, 1000, true);
  await desktop.goto(base, { waitUntil: 'networkidle' });
  const inspect = desktop.getByRole('button', { name: 'A closer look', exact: true });
  await inspect.click();
  await desktop.waitForTimeout(1100);
  assert.equal(await desktop.locator('.hero-inspect').getAttribute('aria-pressed'), 'true');
  assert.equal(await desktop.locator('.hero-front').evaluate(element => getComputedStyle(element).opacity), '1');
  assert.equal(await desktop.locator('.hero-angle').evaluate(element => getComputedStyle(element).opacity), '0');
  assert.equal(await desktop.locator('.hero-detail-notes').getAttribute('aria-hidden'), 'false');
  await desktop.screenshot({ path: path.join(output, 'signature-desktop.png') });
  await desktop.getByRole('button', { name: 'Return to the silhouette', exact: true }).click();
  await desktop.waitForTimeout(1100);
  assert.equal(await desktop.locator('.hero-angle').evaluate(element => getComputedStyle(element).opacity), '1');
  report.workflows.signature = 'Explicit inspection, matching front artwork, annotations, reversible silhouette';
  await jump(desktop, '#object');
  await desktop.getByRole('button', { name: /The artwork/ }).click();
  assert.equal(await desktop.getByRole('button', { name: /The artwork/ }).getAttribute('aria-pressed'), 'true');
  await desktop.getByRole('button', { name: 'Enlarge the artwork' }).click();
  assert(await desktop.getByRole('dialog').isVisible());
  await desktop.keyboard.press('ArrowRight');
  assert((await desktop.locator('#gallery-dialog-title').innerText()).startsWith('The inside'));
  await desktop.keyboard.press('ArrowLeft');
  assert((await desktop.locator('#gallery-dialog-title').innerText()).startsWith('The artwork'));
  await desktop.keyboard.press('Escape');
  assert.equal(await desktop.locator('dialog[open]').count(), 0);
  assert.equal(await desktop.evaluate(() => document.activeElement?.getAttribute('aria-label')), 'Enlarge the artwork');
  for (const name of ['The inside', 'The finishing touch', 'The silhouette']) {
    await desktop.getByRole('button', { name: new RegExp(name) }).click();
    await desktop.locator('.gallery-stage > img').evaluate(img => img.decode());
    await desktop.waitForFunction(() => document.querySelector('.gallery-stage')?.getAttribute('aria-busy') === 'false');
  }
  await desktop.screenshot({ path: path.join(output, 'desktop-gallery.png') });
  report.workflows.gallery = 'All four views, keyboard arrows, Escape, focus restoration';
  await jump(desktop, '#development');
  await desktop.getByText('Can I buy it yet?', { exact: true }).click();
  assert(await desktop.locator('details[open]').innerText().then(text => text.includes('not available to purchase')));
  await desktop.getByText('Can I buy it yet?', { exact: true }).click();
  await desktop.locator('summary').filter({ hasText: 'What will be inside?' }).focus();
  await desktop.keyboard.press('Enter');
  assert(await desktop.locator('.faq[open]').innerText().then(text => text.includes('have not yet been confirmed')));
  report.workflows.faq = 'Pointer and keyboard disclosure';
  await desktop.locator('a.hero-cta').evaluate(element => element.scrollIntoView());
  await desktop.getByRole('link', { name: 'Explore the concept' }).first().click();
  await desktop.waitForTimeout(1500);
  assert(Math.abs((await desktop.locator('#object').boundingBox()).y - 90) < 120);
  report.workflows.primaryCta = 'Navigates to the product study';
  for (const name of ['The intention', 'The object', 'The details']) {
    await desktop.getByRole('navigation', { name: 'Main navigation' }).getByRole('link', { name, exact: true }).click();
    await desktop.waitForTimeout(1400);
    const target = { 'The intention': '#intention', 'The object': '#object', 'The details': '#details' }[name];
    assert(Math.abs((await desktop.locator(target).boundingBox()).y - 24) < 8, `${name}: anchor position`);
  }
  report.workflows.desktopNavigation = 'All three main links align at the specified reading offset';
  await desktop.getByRole('link', { name: 'Back to top', exact: true }).evaluate(element => element.scrollIntoView());
  await desktop.getByRole('link', { name: 'Back to top', exact: true }).click();
  await desktop.waitForTimeout(1400);
  assert((await desktop.evaluate(() => scrollY)) < 5);
  report.workflows.backToTop = true;
  await layout(desktop, 'tablet', 820, 1180);
  await layout(desktop, 'wide', 1920, 1080);
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 });
  watch(mobile);
  await layout(mobile, 'mobile', 390, 844, true);
  await mobile.getByRole('button', { name: 'Open navigation' }).click();
  assert(await mobile.getByRole('dialog', { name: 'Explore Nurture' }).isVisible());
  await mobile.getByRole('navigation', { name: 'Mobile navigation' }).getByRole('link', { name: /The object/ }).click();
  await mobile.waitForTimeout(300);
  assert.equal(await mobile.locator('dialog[open]').count(), 0);
  assert(Math.abs((await mobile.locator('#object').boundingBox()).y) < 200);
  assert.equal(await mobile.evaluate(() => document.body.style.overflow), '');
  await mobile.getByRole('button', { name: 'Open navigation' }).click();
  await mobile.getByRole('dialog', { name: 'Explore Nurture' }).waitFor({ state: 'visible' });
  await mobile.keyboard.press('Escape');
  await mobile.waitForFunction(() => document.querySelector('.menu-toggle')?.getAttribute('aria-expanded') === 'false');
  report.workflows.mobileMenu = 'Open, navigate, Escape, scroll unlock';
  await jump(mobile, '#object');
  await mobile.getByRole('button', { name: 'Enlarge the silhouette' }).click();
  await mobile.getByRole('button', { name: 'Next product view' }).click();
  assert((await mobile.locator('#gallery-dialog-title').innerText()).startsWith('The artwork'));
  await mobile.getByRole('button', { name: 'Close enlarged view' }).click();
  report.workflows.mobileGallery = true;
  await mobile.goto(base, { waitUntil: 'networkidle' });
  await mobile.getByRole('button', { name: 'A closer look', exact: true }).click();
  await mobile.waitForTimeout(1100);
  assert.equal(await mobile.locator('.hero-detail-notes').getAttribute('aria-hidden'), 'false');
  assert.equal(await mobile.locator('.hero-front').evaluate(element => getComputedStyle(element).opacity), '1');
  await mobile.screenshot({ path: path.join(output, 'signature-mobile.png') });
  report.workflows.mobileSignature = true;
  await layout(mobile, 'small-mobile', 320, 740);
  const reduced = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  watch(reduced);
  await reduced.goto(base, { waitUntil: 'networkidle' });
  assert.equal(await reduced.locator('html').evaluate(element => element.classList.contains('lenis')), false);
  assert.equal(await reduced.locator('.hero-word').evaluate(element => getComputedStyle(element).opacity), '1');
  assert.equal(await reduced.locator('.word-inner').first().evaluate(element => getComputedStyle(element).transform), 'none');
  await reduced.screenshot({ path: path.join(output, 'reduced-motion-hero.png') });
  await reduced.getByRole('button', { name: 'A closer look', exact: true }).click();
  await reduced.waitForFunction(() => getComputedStyle(document.querySelector('.hero-front')).opacity === '1');
  assert(['none', 'matrix(1, 0, 0, 1, 0, 0)'].includes(await reduced.locator('.hero-front').evaluate(element => getComputedStyle(element).transform)));
  report.accessibility.reducedMotion = 'Native scroll, visible final content, instant signature alternative';
  const noJs = await browser.newPage({ viewport: { width: 390, height: 844 }, javaScriptEnabled: false });
  watch(noJs);
  await noJs.goto(base, { waitUntil: 'networkidle' });
  assert(await noJs.getByRole('heading', { level: 1 }).isVisible());
  assert(await noJs.getByRole('navigation', { name: 'Main navigation' }).isVisible());
  await noJs.getByRole('link', { name: 'Explore the concept' }).first().click();
  assert(await noJs.locator('.no-js-note').isVisible());
  assert.equal(await noJs.locator('.no-js-note a').count(), 3);
  await noJs.getByText('Can I buy it yet?', { exact: true }).click();
  assert(await noJs.locator('.faq[open]').innerText().then(text => text.includes('not available to purchase')));
  await noJs.screenshot({ path: path.join(output, 'no-javascript-mobile.png'), fullPage: true });
  report.accessibility.noJavaScript = 'Full prerendered page, navigation, image links, native FAQ';
  const keyboard = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  watch(keyboard);
  await keyboard.goto(base, { waitUntil: 'networkidle' });
  await keyboard.keyboard.press('Tab');
  assert.equal(await keyboard.evaluate(() => document.activeElement.textContent), 'Skip to content');
  const focus = await keyboard.evaluate(() => getComputedStyle(document.activeElement).outlineStyle);
  assert.notEqual(focus, 'none');
  report.accessibility.keyboard = 'First tab skip link with visible focus; native modal focus trap';
  const failurePage = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  await failurePage.route('**/assets/product/top*.webp', route => route.fulfill({ status: 404, body: '' }));
  await failurePage.goto(base, { waitUntil: 'networkidle' });
  await jump(failurePage, '#object');
  await failurePage.getByRole('button', { name: /The finishing touch/ }).click();
  await failurePage.getByRole('status').filter({ hasText: 'This view could not be loaded' }).waitFor();
  assert(await failurePage.getByRole('button', { name: 'Enlarge the finishing touch' }).isDisabled());
  await failurePage.getByRole('button', { name: /The silhouette/ }).click();
  await failurePage.waitForFunction(() => document.querySelector('.gallery-stage')?.getAttribute('aria-busy') === 'false');
  assert.equal(await failurePage.locator('.media-error').count(), 0);
  report.workflows.mediaFailure = 'Real image error, disabled enlargement, recovery by selecting another view';
  const { default: AxeBuilder } = await import('@axe-core/playwright');
  const axe = await new AxeBuilder({ page: desktop }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
  report.accessibility.axe = { passes: axe.passes.length, violations: axe.violations.map(item => ({ id: item.id, impact: item.impact, nodes: item.nodes.map(node => node.target) })), incomplete: axe.incomplete.map(item => item.id) };
  assert.equal(axe.violations.length, 0, `Axe violations: ${JSON.stringify(report.accessibility.axe.violations)}`);
  assert.equal(errors.length, 0, `Browser errors: ${errors.join('\n')}`);
  assert.equal(failedResponses.length, 0, `HTTP errors: ${failedResponses.join('\n')}`);
  report.passed = true;
} catch (error) {
  report.passed = false;
  report.failure = error.stack;
  throw error;
} finally {
  await writeFile(path.join(output, 'report.json'), JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));
  await browser.close();
}
